---
output:
  md_document:
    variant: markdown_github
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-"
)
```

```{r echo=FALSE, results="hide", message=FALSE}
#library()
```

# wildlifedetectR

`wildlifedetectR` provides a collection of functions for running typical wildlife forensic tests. This package is in development.


* get the latest development version from github with

```R
    # install.packages("devtools")
    # building vignettes might take some time. Set build_vignettes = FALSE for a quick download.
    devtools::install_github("elhumble/wildlifedetectR", build_vignettes = TRUE)
    # Individualisation tutorial
    data(BadgerRefPop)
    data(BadgerTrace)
    individualisation(db = BadgerRefPop,
                      unknown = BadgerTrace,
                      Th = 0.1,
                      allele_freq = T,
                      known_alleles = T)
```

### Authors
E Humble & K Ewart

    

